# Lista2
**Disciplina:** Python para Ciências de Dados
**Professor:** Gabriel Oliveira Assunção

# **Aluna:** Clara Cabral Lisboa

# Exercício 1:

Desejamos calcular a correção de um índice (valor entre 0 e 1), a correção é dada por:


* Se índice está no intervalo [0.6, 1] então multiplique por 0.8
* Se índice está no intervalo [0.2, 0.6) então multiplique por 0.85
* Se o índice está no intervalo [0, 0.2) então multiplique por 0.9.

Exemplo:

Índice = 0.6; índice corrigido 0.48

Índice = 0.7; índice corrigido 0.56

Índice = 0.2; índice corrigido 0.17

Índice = 0.1; índice corrigido 0.09

Escreva duas funções para realizar esta transformação, ambas as funções devem ter a mesma entrada e mesma saída, a diferença das funções é:

* Em uma função deve ser utilizado apenas condição e loop para realizar a transformação dos dados que será recebido em um array (Função exercicio_1_a)
* Na outra função deverá ser utilizada apenas operações com arrays. (Função exercicio_1_b). Obs.: pode ser utilizada operações lógicas com array (array > 1).

**Entrada**: array como valor entre 0 e 1

**Saída**: array com os valores corrigidos


In [50]:
import numpy as np
#Exemplo
entrada = np.array([0.13710655, 0.02993014, 0.34184833, 0.67633817, 0.43331636, 0.43511794, 0.04085725, 0.33685067, 0.1500961 , 0.69869715])
saida = np.array([0.1233959 , 0.02693712, 0.29057108, 0.54107053, 0.36831891, 0.36985025, 0.03677152, 0.28632307, 0.13508649, 0.55895772])

In [51]:
## Para geração de números aleatorios

np.random.seed(15) ##pode definir a semente que quiser
np.random.random(10) ##pode definir o tamanho de array que quiser

array([0.8488177 , 0.17889592, 0.05436321, 0.36153845, 0.27540093,
       0.53000022, 0.30591892, 0.30447436, 0.11174128, 0.24989901])

In [73]:
## EXERCÍCIO 1 A:  Utilizar apenas condição e loop

import numpy as np
def correcao_cond_loop(entrada_1a):
  saida_1a=entrada_1a
  k=0
  
  #Condição para correção do valor
  for i in entrada_1a:
    if i >= 0.6:
      saida_1a[k] = i*0.8
    elif i< 0.6 and i > 0.2:
      saida_1a[k] = i*0.85
    else:
      saida_1a[k] = i*0.9
    
    k+=1

  return saida_1a


entrada_1a=np.random.seed(15)
entrada_1a=np.random.random(10)

correcao_cond_loop(entrada_1a)

array([0.67905416, 0.16100633, 0.04892689, 0.30730768, 0.23409079,
       0.45050019, 0.26003108, 0.25880321, 0.10056715, 0.21241416])

In [72]:
## EXERCÍCIO 1 B:  Utilizar apenas operações com array

def correcao_operacao_array(entrada_1b):
  saida_1b=entrada_1b
  saida_1b = np.where (entrada_1b >= 0.6, saida_1b*0.8, saida_1b)
  saida_1b = np.where ((entrada_1b >= 0.2) & (entrada_1b < 0.6), saida_1b*0.85, saida_1b)
  saida_1b = np.where (entrada_1b < 0.2, saida_1b*0.9, saida_1b)

  return saida_1b

entrada_1b=np.random.seed(15)
entrada_1b=np.random.random(10)
correcao_operacao_array(entrada_1b)

array([0.67905416, 0.16100633, 0.04892689, 0.30730768, 0.23409079,
       0.45050019, 0.26003108, 0.25880321, 0.10056715, 0.21241416])

# Exercício 2

Medidas de similaridades são importantes em diversas aplicações em ciência de dados, como por exemplo algoritmos de clusterização e NLP.

Medidas de similaridade são métricas que indicam o quão dois vetores (pontos) são similares entre si, ou o quão dois conjuntos são similares entre si. Alguns exemplos de medidas de similaridade são:

Implemente uma função que calcule cada uma das seguintes medidas:

## a) Distância euclidiana

Calcula-se a distância de dois pontos. Pode ser utilizado em algoritmos de clusterização para identificar observações parecidas.

$d(a,b) = \sqrt{\sum_{i=1}^n(a_i - bi)^2}$,

n é o tamanho do meu espaço (2-dimensões n=2; 3-dimensões n=3) e em algoritmos de clusterização representa o número de features.


Exemplo:

a = (1, 2)
b = (3, 5)


$d(a,b) = \sqrt{(1-3)^2 + (2-5)^2} = \sqrt{2^2 + 3^2} = \sqrt{13}$

Para a função
**Entrada**: dois arrays de dimensão 1 para se calcular a distância. Obs: o formato (tamanho do array) deve ser o mesmo.


**Saída**: valor da distância

In [ ]:
from typing import Tuple
def gera_dados_1(n: int) -> Tuple[np.array, np.array]:
  """Gera vetores para as letras a, b e c

  :param n: Tamanho do array
  :type n: int

  :return:
    Tuple[np.array, np.array]: retorna dois arrays para se calcular a similaridade.

  """
  import numpy as np

  np.random.seed(15)

  array_1 = np.random.normal(n)
  array_2 = np.random.normal(n)

  return array_1, array_2

In [74]:
## EXERCÍCIO 2 A: 

import numpy as np
def distancia_euclidiana(a,b)->float:
     
     distancia_euc=np.sqrt(np.sum(np.square(a-b)))

     return distancia_euc

np.random.seed(15)

a=np.random.normal(size=5) 
b=np.random.normal(size=5)

distancia_euclidiana(a,b)


2.3613552430212073

## b) Distância de Manhattan

Outra forma de calcular a distância entre dois pontos. Também pode ser utilizada em algoritmos de clusterização.

$d(a,b) = \sum_{i=1}^n |a_i-b_i|$

A interpretação de n para clusterização é a mesma que da distância euclidiana.

Exemplo:

a = (1, 2)
b = (3, 5)

$d(a,b) = 5$

**Entrada**: dois arrays de dimensão 1 para se calcular a distância. Obs: o formato (tamanho do array) deve ser o mesmo.

**Saída**: valor da distância

In [76]:
##EXERCÍCIO 2 B:

import numpy as np 
def distancia_manhattan(c,d):
     
     distancia_mt = np.sum(np.abs(c-d))

     return distancia_mt

np.random.seed(15)
c=np.random.normal(size=5)
d=np.random.normal(size=5)

distancia_manhattan(c,d)

4.724217617672255

## c) Cosseno similaridade

Uma métrica muito utilizada, especialmente em NLP, para comparar a similaridade de dois vetores é a cosseno similaridade (calcula o cosseno do ângulo entre os vetores)

$sim(a, b) = \frac{\sum_{i=1}^n a_i * b_i}{\sqrt{\sum_{i=1}^n a_i^2} \sqrt{\sum_{i=1}^n b_i^2}}$

Obs.: os valores de similaridade estarão entre 1 (muita similaridade) e -1 (vetores opostos)

Exemplo:

a = (1, 2)
b = (3, 5)

$sim(a,b) = \frac{1*3 + 2*5}{\sqrt{1^2+2^2}\sqrt{3^2+5^2}}=0.99$

**Entrada**: dois arrays de dimensão 1 para se calcular a similaridade. Obs: o formato (tamanho do array) deve ser o mesmo.


**Saída**: valor similaridade

In [77]:
#EXERCÍCIO 2 C:

def cosseno_similaridade(e,f):
    
    cosseno_sim = np.sum(e*f)/(np.sqrt(np.sum(e**2))*np.sqrt(np.sum(f**2)))
    return cosseno_sim

np.random.seed(15)
e=np.random.normal(size=5)
f=np.random.normal(size=5)

cosseno_similaridade(e,f)

0.21935762127676645

## d) Jaccard índice:

O índice de Jaccard mede a similaridade de dois conjuntos, possui aplicação em NLP para verificar se duas frases têm vocabulário bem similar. Dado um conjunto A e B o índice de Jaccard é calculado como:

$Jaccard = \frac{|A \cap B|}{|A \cup B|}$

Em NLP podemos representar uma frase através de um array de dimensão 1 onde cada posição indica se uma palavra apareceu ou não na frase. Exemplo:


|Frase|oi|meu|nome|é|gabriel|pedro|
|----|---|---|----|---|----|----|
|oi meu nome é gabriel|1|1|1|1|1|0|
|oi meu nome é pedro|1|1|1|1|0|1|

Frase A: "oi meu nome é gabriel": [1, 1, 1, 1, 1, 0]

Frase B: "oi meu nome é pedro": [1, 1, 1, 1, 0, 1]

$Jaccard = \frac{4}{6}$

**Entrada**: dois arrays de dimensão 1 para se calcular o índice. Obs: o formato (tamanho do array) deve ser o mesmo e ele deve ser preenchido com apenas zeros e um.

**Saída**: valor do índice

# **Errata Lista 2**

No exercício de índice de Jaccard os vetores de input podem conter zero em duas posições.


 

Exemplo:

Array 1 = [0, 1, 1, 0, 1]

Array 2 = [0, 1, 0, 1, 1]

Índice = 2/4

Existem duas posições com valor 1 em ambos o array e existem 4 posições preenchidas nos dois arrays. No exemplo de texto pense que o vocabulário utilizado para construir os arrays seja {casa, oi, boa, tarde, noite} e a representação do array é a seguinte:

 



vocabulario
casa 
oi
boa
tarde
noite

frase 1
0
1
1
0
1

frase 2
0
1
0
1
1



Primeira frase: oi boa noite

Segunda frase: oi boa tarde

Nós temos 2 palavras em comum em um vocabulário de 4 palavras destas frases.

In [57]:
from typing import Tuple
def gera_dados_2(n: int) -> Tuple[np.array, np.array]:
  """Gera vetores para a letra d

  :param n: Tamanho do array
  :type n: int

  :return:
    Tuple[np.array, np.array]: retorna dois arrays para se calcular a similaridade.

  """
  import numpy as np

  np.random.seed(15)

  array_1 = np.random.choice([0, 1], size=(n,), p=[0.25, 0.75])

  array_2 = np.random.choice([0, 1], size=(n,), p=[0.5, 0.5])
  return array_1, array_2

In [78]:
## EXERÍCIO 2 D:

import numpy as np
def jaccard(frase_a, frase_b):

    frases_ab=frase_a+frase_b


    jac = np.sum((frases_ab)==2)/np.sum((frases_ab)>=1)
    return jac

np.random.seed(15)
frase_a = np.random.choice([0, 1], size=(5), p=[0.25, 0.75])
frase_b = np.random.choice([0, 1], size=(5), p=[0.5, 0.5])

jaccard(frase_a,frase_b)

0.3333333333333333