## Frameworks para Deep Learning

# **Tensores em PyTorch**

**Clara Cabral Lisboa**

In [1]:
import torch

## **Criando Tensores**
Crie um tensor 1D de números inteiros de 1 a 5.

In [2]:
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print(tensor_1d)

tensor([1, 2, 3, 4, 5])


Crie um tensor 2D de números reais de 0 a 8 em uma matriz 2x4.

In [3]:
tensor_2d = torch.linspace(0, 8, steps=8).view(2, 4)
print(tensor_2d)

tensor([[0.0000, 1.1429, 2.2857, 3.4286],
        [4.5714, 5.7143, 6.8571, 8.0000]])


##**Operações Básicas**

Multiplique o tensor 1D do exercicio anterior por 3

In [4]:
tensor_1d_mult = tensor_1d * 3
print(tensor_1d_mult)

tensor([ 3,  6,  9, 12, 15])


Calcule o produto escala do tensor do exercício anterior com o tensor 1D criado na célula abaixo

In [5]:
tensor_1d_new = torch.LongTensor([-1, -10, 0, 2, 3])
produto_escalar = torch.dot(tensor_1d_mult, tensor_1d_new)
print(produto_escalar)
print(tensor_1d_new)

tensor(6)
tensor([ -1, -10,   0,   2,   3])


##**Operações Avançadas**

Crie um tensor 1D de números inteiros de 1 a 16 e utilize o método view para transformar o tensor em uma matriz 4x4.

In [6]:
tensor_1d_16 = torch.arange(1, 17)
tensor_4x4 = tensor_1d_16.view(4, 4)
print(tensor_4x4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


Divida o tensor 1D de 1 a 16 em 4 partes iguais.

In [7]:
partes = torch.chunk(tensor_1d_16, 4)
for parte in partes:
    print(parte)

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])
tensor([ 9, 10, 11, 12])
tensor([13, 14, 15, 16])


Crie um novo tensor 2D empilhando essas partes verticalmente.

In [8]:
tensor_empilhado = torch.stack(partes, dim=1)
print(tensor_empilhado)

tensor([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]])
